/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * Este archivo es un ejemplo para mostrar la configuración de pines GPIO
 * en los STM32F4 y el uso de bit-banding para manipulación eficiente de bits.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"



int main(void)
{
    // 1. Habilitar el reloj para los puertos GPIOD y GPIOA
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN | RCC_AHB1ENR_GPIOAEN;
    RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
    // 2. Configurar los pines PD12-PD15 como salida (MODER = 01)
    GPIOD->MODER &=~ (GPIO_MODER_MODE12 | GPIO_MODER_MODE13 | GPIO_MODER_MODE14 |
            GPIO_MODER_MODE15); // Limpia los bits
    GPIOD->MODER |= GPIO_MODER_MODE12_0 | GPIO_MODER_MODE13_0 | GPIO_MODER_MODE14_0 |
            GPIO_MODER_MODE15_0; // Configura como salida

    // Configurar PA0 como entrada (MODER = 00)
    GPIOA->MODER &=~ (GPIO_MODER_MODE0);

    /*EXTI*/
    EXTI->FTSR |= EXTI_FTSR_TR0;
    EXTI->IMR |= EXTI_IMR_IM0;

    SYSCFG->EXTICR[0] &=~ SYSCFG_EXTICR1_EXTI0;
    SYSCFG->EXTICR[0] |= SYSCFG_EXTICR1_EXTI0_PA;

    NVIC_EnableIRQ(EXTI0_IRQn);

    NVIC_SetPriority(EXTI0_IRQn, 4);
    // Bucle infinito
    for(;;){
        // Aquí se puede agregar lógica para parpadear LEDs, leer botones, etc.
    }
}
void EXTI_GPIO_Callback(uint32_t pin)
{
	switch(pin)
	{
	case 0:
		printf("PA0->IT\r\n");
		break;
	case 1:
		break;
	}
}
// Redirección de printf al canal ITM para debug
int __io_putchar(int ch){
    /*Cortex-M3/M4/M7/M33/23...*/
    ITM_SendChar(ch);
    return ch;
}
