/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"

/**
 * NUCLEO-64
 * PA5->LED
 * PC13->SWITCH
 *
 * STM32F4-Discovery
 * PD12-15->leds
 * PA0->Boton
 *
 * NUCLEO-32
 * LED->PB3
 */

/**
 * PD12
 * bit_word_addr = 42000000U + ((0x020C00 + 0x14) * 0x20 + 0xC*0x4
 */

//#define LED1 *((volatile uint32_t *)(42000000U + (0x020C00 + 0x14) * 0x20 + 0xC*0x4))
#define BITBAND_ACCESS(a, b)  *(volatile uint32_t*)(((uint32_t)&a & 0xF0000000) + 0x2000000 + (((uint32_t)&a & 0x000FFFFF) << 5) + (b << 2))

#define LED1 BITBAND_ACCESS(GPIOD->ODR, 12)


typedef struct
{
	volatile uint32_t BIT0;
	volatile uint32_t BIT1;
	volatile uint32_t BIT2;
	volatile uint32_t BIT3;
	volatile uint32_t BIT4;
	volatile uint32_t BIT5;
	volatile uint32_t BIT6;
	volatile uint32_t BIT7;
	volatile uint32_t BIT8;
	volatile uint32_t BIT9;
	volatile uint32_t BIT10;
	volatile uint32_t BIT11;
	volatile uint32_t BIT12;
	volatile uint32_t BIT13;
	volatile uint32_t BIT14;
	volatile uint32_t BIT15;
}GPIO_ODR_BB_t;

#define GPIOD_BB_ODR ((GPIO_ODR_BB_t *)(PERIPH_BB_BASE + 0x418280))


int main(void)
{
	/*1. ubicar el bus y habilitar el reloj*/
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN | RCC_AHB1ENR_GPIOAEN;
	/*2. configurar el registro moder*/
	//PD12-15
	GPIOD->MODER &=~ (GPIO_MODER_MODE12 | GPIO_MODER_MODE13 | GPIO_MODER_MODE14 |
			GPIO_MODER_MODE15);

//	GPIOD->MODER &=~ (0x7F)<<GPIO_MODER_MODE12_Pos;//0b1111 1111
	GPIOD->MODER |= GPIO_MODER_MODE12_0 | GPIO_MODER_MODE13_0 | GPIO_MODER_MODE14_0 |
			GPIO_MODER_MODE15_0;
	//PA0
	GPIOA->MODER &=~ (GPIO_MODER_MODE0);
//GPIOD->MODER |= 0x55<<GPIO_MODER_MODE12_Pos;//0b0101 0101->0x55
	/*3. En caso de salida*/
	GPIOD->OTYPER = 0;
	/*4. Resistencias pull0 up/down*/
	GPIOA->PUPDR &=~ (GPIO_PUPDR_PUPD0);
//	GPIOA->PUPDR |= GPIO_PUPDR_PUPD0_0;

	GPIOD->ODR |= GPIO_ODR_OD12; //Alto el pd12
	GPIOD->ODR &=~ GPIO_ODR_OD12; //Borra//and, not

	GPIOD->BSRR |= GPIO_BSRR_BS12; //or
	GPIOD->BSRR |= GPIO_BSRR_BR12;

	*((volatile uint32_t *)0x20000300) |= 1<<2;
	*((volatile uint32_t *)0x20000300) &=~ 1<<2;

	*((volatile uint32_t *)0x22006008) = 1;
	*((volatile uint32_t *)0x22006008) = 0;
	//0x22000000U->SRAM
	//0x42000000U->PERIFERICOS
	LED1 = 1;
	LED1 = 0;

	GPIOD_BB_ODR->BIT12 = 1;
	GPIOD_BB_ODR->BIT15 = 1;
	GPIOD_BB_ODR->BIT15 = 0;
    /* Loop forever */
	for(;;){

	}
}



int __io_putchar(int ch){

	/*Cortex-M3/M4/M7/M33/23...*/
	ITM_SendChar(ch);

	return ch;
}
