/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//----------------------------------------------------------------------------
// Includes
//----------------------------------------------------------------------------
#include <stdint.h>
#include "main.h"
#include "stm32f4xx.h"//CMSIS
#include <stdio.h>

//----------------------------------------------------------------------------
// defines
//----------------------------------------------------------------------------

//----------------------------------------------------------------------------
// constant
//----------------------------------------------------------------------------
#define SYSTICK_CTRL *((volatile uint32_t *)(0xE000E010))

#define SYSCON0 *((volatile uint32_t *)(0x400740C4))
/**
 * ->variables
 * volatile
 * - accedido por el procesador de forma rapida
 * - para hacer referencia a registros o hardware
 *   la variable puede ser modificada por el software o programa o puede ser modificado
 *   por un agente externo (hardware)
 * extern
 *  definido en otro lado(archivo)
 * static
 *  variable solo visible dentro del archivo o funcion
 */
//----------------------------------------------------------------------------
// global variables
//----------------------------------------------------------------------------

//----------------------------------------------------------------------------
// function prototype
//----------------------------------------------------------------------------
void app_clock_config(uint8_t source);
void delay_ms(uint32_t delay);
//----------------------------------------------------------------------------
// main
//----------------------------------------------------------------------------
int main(void)
{
	/**
	 * NOMBRE DE BLOQUE -> NOMBRE DE REGISTRO
	 */
	app_clock_config(APP_USE_PLL);
	//enable clock GPIOD
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
	//GPIO
	//->CONTROL
	/*
	 * MODER
	 * funcion del pin: entrada (floating), salida digital, funcion alternativa, analogica
	 * 00: floating
	 * 01: general purpuse output
	 * 10: alternative function
	 * 11: analog
	 *
	 * OTYPER
	 * 0: push pull
	 * 1: open-drain
	 *
	 * OSPEEDR
	 * 00: low speed
	 * 01: medium speed
	 * 10: high speed
	 * 11: very high speed
	 *
	 * PUPDR
	 * 00: no pull up/down
	 * 01: pull up
	 * 10: pull down
	 * 11: reserved
	 *
	 * AFRL
	 * 0-7 pines
	 * AFRH
	 * 8-15 pines
	 */
	//PD12-15: LED0-3
	GPIOD->MODER &=~ (GPIO_MODER_MODE12 | GPIO_MODER_MODE13 | GPIO_MODER_MODE14 | GPIO_MODER_MODE15);
	GPIOD->MODER |= GPIO_MODER_MODE12_0 | GPIO_MODER_MODE13_0 | GPIO_MODER_MODE14_0 | GPIO_MODER_MODE15_0;

	//REGISTROS DE DATOS
	/*
	 * ODR
	 * escribir bits en el puerto
	 *
	 * IDR
	 * leer bist del puerto
	 *
	 */
	GPIOD->ODR |= GPIO_ODR_OD12;

	uint8_t pinvalue = (GPIOD->IDR & GPIO_IDR_ID12) ? 1 : 0;

	pinvalue = (GPIOD->IDR >>12) & 0x1;

	if(pinvalue)
	{
		//todo
	}
	//REGISTROS DE MANIPULACION BIT A BIT
	/**
	 * BSRR : bit set/reset register
	 * 0-15: set
	 * 16-31: reset (16 + #pin)
	 * BRR: bit reset register
	 */
	GPIOD->BSRR = GPIO_BSRR_BS13 | GPIO_BSRR_BS14 | GPIO_BSRR_BR12;


	/**
	 * LCKR
	 * LOCK
	 */
	GPIOD->LCKR |= GPIO_LCKR_LCK12;


	volatile uint32_t *CTRL = (volatile uint32_t *)(0xE000E010);

	*CTRL |= 1;

	//systick
	SysTick->CTRL = 0;
	SysTick->VAL = 0;
	SysTick->LOAD = SystemCoreClock / (1000) - 1; // 2^24

	SysTick->CTRL |= SysTick_CTRL_CLKSOURCE_Msk | SysTick_CTRL_ENABLE_Msk;


	/* Loop forever */
	for(;;)
	{
		GPIOD->ODR ^= GPIO_ODR_OD15;
		delay_ms(100);
	}
}

//----------------------------------------------------------------------------
// function definition
//----------------------------------------------------------------------------
void delay_ms(uint32_t delay)
{
	for(uint32_t i = 0; i<delay; i++)
	{
		while(!(SysTick->CTRL & SysTick_CTRL_COUNTFLAG_Msk)); //loop (1ms)

	}
}


void app_clock_config(uint8_t source)
{

	//Switch Internal clock
	RCC->CR |= RCC_CR_HSION;
	while((RCC->CR & RCC_CR_HSIRDY) == 0);

	RCC->CFGR &=~ RCC_CFGR_SW;
	RCC->CFGR |= RCC_CFGR_SWS_HSI;
	while((RCC->CFGR & RCC_CFGR_SWS_HSI) != (RCC_CFGR_SWS_HSI));
	FLASH->ACR &=~ FLASH_ACR_LATENCY;
	//HSI16->Por defecto

	switch(source)
	{
	case APP_USE_HSE:
	{
		//HSE on
		RCC->CR |= RCC_CR_HSEON;
		while(!(RCC->CR & RCC_CR_HSERDY));
		//select clock
		RCC->CFGR |= RCC_CFGR_SW_HSE;
		while((RCC->CFGR & RCC_CFGR_SWS_HSE) != (RCC_CFGR_SWS_HSE));

		break;
	}
	case APP_USE_MSI:
	{

	}
	case APP_USE_PLL:
	{
		//PLL off
		RCC->CR &=~ RCC_CR_PLLON;
		while(RCC->CR & RCC_CR_PLLRDY);
		//configurar los valores del PLL
		/**
		 * fclock_p = ((16/8 ) * 168 )/2 = 168MHZ
		 */
		//source
		RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLSRC;
		RCC->PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSI;
		//M
		RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLM;
		RCC->PLLCFGR |= RCC_PLLCFGR_PLLM_3; //BITS (bit 3) 0b1000->8
		//N
		RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLN;
		RCC->PLLCFGR |= 168<<RCC_PLLCFGR_PLLN_Pos;
		//P
		RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLP;
		//Valor maximo del bus APB1(42MHZ)
		RCC->CFGR &=~ RCC_CFGR_PPRE1;
		RCC->CFGR |= RCC_CFGR_PPRE1_DIV4;
		//valor maximo del bus APB2(84MHZ)
		RCC->CFGR &=~ RCC_CFGR_PPRE2;
		RCC->CFGR |= RCC_CFGR_PPRE2_DIV2;
		//latencia
		FLASH->ACR &=~ FLASH_ACR_LATENCY;
		FLASH->ACR |= FLASH_ACR_LATENCY_5WS;
		//seleccionar la fuente
		RCC->CR |= RCC_CR_PLLON;
		while(!(RCC->CR & RCC_CR_PLLRDY));

		RCC->CFGR &=~RCC_CFGR_SW;
		RCC->CFGR |= RCC_CFGR_SW_PLL;
		while((RCC->CFGR & RCC_CFGR_SWS_PLL) != (RCC_CFGR_SWS_PLL));
		break;
	}
	}

	uint8_t temp = RCC->CFGR & 0x3; //[1:0]

	//update core clock
	SystemCoreClockUpdate();

	switch(temp)
	{
	case APP_USE_HSI:
		printf("la aplicacion esta usando HSI:%lu\r\n", SystemCoreClock);
		break;
	case APP_USE_HSE:
		printf("la aplicacion esta usando HSE:%lu\r\n",SystemCoreClock);
		break;
	case APP_USE_PLL:
		printf("la aplicacion esta usando PLL:%lu\r\n", SystemCoreClock);
		break;
	}
}
int __io_putchar(int ch)
{
	//aplica: ARM CORTEX-M3/4/7/33..
	//No aplica para los CORTEX-M0/M0+
	//SWO (PB3--->stlink)
	ITM_SendChar(ch);

	return ch;
}
