/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Cuerpo principal del programa
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * Todos los derechos reservados.
 *
 * Este archivo es un ejemplo para mostrar la configuración de pines GPIO
 * en los STM32F4 y el uso de bit-banding para manipulación eficiente de bits.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "delay.h"

/*----------------------------------------------------------------------------*/
/* Defines */
/*----------------------------------------------------------------------------*/
// Macro para habilitar el reloj de un periférico GPIO específico
#define RCC_AHB1ENR_CLK_ENABLE(a) RCC->AHB1ENR |= RCC_AHB1ENR_GPIO ##a ##EN

/*----------------------------------------------------------------------------*/
/* Typedefs */
/*----------------------------------------------------------------------------*/
// Definición de un tipo para la estructura del botón
typedef struct button button_t;

// Definición de un tipo para el puntero a la función de evento del botón
typedef void(*button_fn)(button_t *obj,uint8_t state);

// Definición de un tipo para el puntero a la función de lectura del botón
typedef uint8_t (*button_read_fc)(uint8_t button);

// Definición de la estructura del botón
struct button
{
    uint8_t state;		// Estado actual del botón
    uint32_t flags;		// Flags del botón
    uint32_t ticks;		// Contador de ticks para el debounce
    button_fn fc;		// Puntero a la función de evento del botón
    button_read_fc read;	// Puntero a la función de lectura del botón
    uint8_t number;		// Número del botón
    uint32_t keepalive;	 // Tiempo que el botón se mantiene presionado
};

// Definición de un tipo para el enum de eventos del botón
typedef enum button_evt
{
    BUTTON_ON_PRESS = 0,	// Evento cuando el botón es presionado
    BUTTON_KEEP_ALIVE,		// Evento mientras el botón se mantiene presionado
    BUTTON_ON_RELEASE,		// Evento cuando el botón es liberado
}button_evt_t;

/*----------------------------------------------------------------------------*/
/* Private variables */
/*----------------------------------------------------------------------------*/
// Instancia de la estructura del botón
button_t sw = {
        .fc = button_sw_event,	// Asigna la función de evento del botón
        .read = button_sw_read,	// Asigna la función de lectura del botón
};

/*----------------------------------------------------------------------------*/
/* Function Prototypes */
/*----------------------------------------------------------------------------*/
// Prototipo de la función para procesar el botón
void button_process(button_t *obj);
// Prototipo de la función para manejar los eventos del botón
void button_sw_event(button_t *obj, uint8_t evt);
// Prototipo de la función para leer el estado del botón
uint8_t button_sw_read(uint8_t pin);
// Prototipo de la función para redireccionar printf al canal ITM
int __io_putchar(int ch);

/*----------------------------------------------------------------------------*/
/* Function definition */
/*----------------------------------------------------------------------------*/

/**
 * @brief Procesa la máquina de estados del botón.
 *
 * Esta función implementa una máquina de estados para manejar los eventos de presionar,
 * mantener presionado y liberar el botón. Utiliza un mecanismo de debounce para evitar
 * transiciones falsas.
 *
 * @param obj: Puntero al objeto botón.
 */
void button_process(button_t *obj)
{
    uint8_t pin = 0;
    switch(obj->state)
    {
    case 0: // no presionado
        // Si el botón es presionado (la lectura devuelve 1), inicia el proceso de debounce.
        if(obj->read(obj->number) == 1)
        {
            obj->ticks = ticksGet(); // Guarda el valor actual del contador de ticks.
            obj->state = 1;		   // Transiciona al estado de debounce.
        }
        break;
    case 1: // debounce
        // Espera un tiempo específico (20ms) para el debounce del botón.
        if((ticksGet() - obj->ticks)>=20)//10-30ms botones <<100ms
        {
            // Si el botón sigue presionado después del tiempo de debounce, se considera una presión válida.
            if(obj->read(obj->number) == 1)
            {
                // Genera el evento on press
                obj->fc(obj,BUTTON_ON_PRESS); // Llama a la función de evento del botón con el evento ON_PRESS.
                obj->state = 2;				   // Transiciona al estado de mantener presionado.
                obj->keepalive = 0;			   // Resetea el contador de mantener presionado.
                obj->ticks = ticksGet();	   // Guarda el valor actual del contador de ticks.
                obj->flags |= 1;			   // Establece un flag indicando que el botón está actualmente presionado.
            }
        }else if(obj->read(obj->number) == 0)
        {
            obj->state = 0;		// Transiciona de vuelta al estado de no presionado si el botón es liberado durante el debounce.
            obj->ticks = 0;		// Resetea el contador de ticks.
        }
        break;
    case 2: // mantener presionado
        pin = obj->read(obj->number);
        // Si el botón se mantiene presionado por un tiempo específico (100ms), genera un evento de mantener presionado.
        if(((ticksGet() - obj->ticks) >= 100) && (pin == 1))
        {
            obj->ticks = ticksGet();	// Guarda el valor actual del contador de ticks.
            obj->keepalive += 100;		// Incrementa el contador de mantener presionado.
            obj->fc(obj, BUTTON_KEEP_ALIVE); // Llama a la función de evento del botón con el evento KEEP_ALIVE.
        }else if(pin == 0)
        {
            // Liberado
            obj->fc(obj,BUTTON_ON_RELEASE); // Llama a la función de evento del botón con el evento ON_RELEASE.
            obj->state = 0;				   // Transiciona de vuelta al estado de no presionado.
            obj->ticks = 0;				   // Resetea el contador de ticks.
            obj->keepalive = 0;			   // Resetea el contador de mantener presionado.
            obj->flags &=~ 1;			   // Limpia el flag de presionado.
        }
        break;
    }
}

/**
 * @brief Maneja los eventos del botón.
 *
 * Esta función es llamada cuando ocurre un evento del botón (presionar, mantener presionado o liberar).
 * Realiza acciones basadas en el evento específico.
 *
 * @param obj: Puntero al objeto botón.
 * @param evt: El tipo de evento del botón (BUTTON_ON_PRESS, BUTTON_KEEP_ALIVE o BUTTON_ON_RELEASE).
 */
void button_sw_event(button_t *obj, uint8_t evt)
{
    switch(evt)
    {
    case BUTTON_ON_PRESS:
        printf("button on press\r\n");
        GPIOD->BSRR = GPIO_BSRR_BS12; // Establece el pin 12 del puerto D en alto (enciende el LED).
        break;
    case BUTTON_KEEP_ALIVE:
        printf("button: %d ms\r\n",(int) obj->keepalive); // Imprime el tiempo que se mantiene presionado el botón en milisegundos.
        break;
    case BUTTON_ON_RELEASE:
        printf("button on release\r\n");
        GPIOD->BSRR = GPIO_BSRR_BR12; // Resetea el pin 12 del puerto D en bajo (apaga el LED).
        break;
    }
}

/**
 * @brief Lee el estado del botón.
 *
 * Esta función lee el estado del pin del botón especificado.
 *
 * @param pin: El número del pin del botón.
 * @return 1 si el botón está presionado, 0 en caso contrario.
 */
uint8_t button_sw_read(uint8_t pin)
{
    if(GPIOA->IDR & GPIO_IDR_ID0)
    {
        return 1;
    }
    return 0;
}

/**
 * @brief Función principal.
 *
 * Este es el punto de entrada del programa. Inicializa el hardware,
 * configura el temporizador SysTick y entra en el bucle principal.
 *
 * @return int: El valor de retorno del programa.
 */
int main(void)
{
    uint32_t ticks = 0;
    RCC_AHB1ENR_CLK_ENABLE(D); // Habilita el reloj para el puerto D.
    RCC_AHB1ENR_CLK_ENABLE(A); // Habilita el reloj para el puerto A.

    // LED1
    GPIOD->MODER &=~ GPIO_MODER_MODE12; // Limpia los bits de modo para el pin 12 del puerto D.
    GPIOD->MODER |= GPIO_MODER_MODE12_0; // Establece el pin 12 del puerto D en modo de salida.
    // SW
    GPIOA->MODER &=~GPIO_MODER_MODE0; // Limpia los bits de modo para el pin 0 del puerto A.

    SysTick_Config(16000); // Configura el temporizador SysTick para generar una interrupción cada 1ms (asumiendo un reloj de 16MHz).

    ticks = ticksGet();
    for(;;){
        // Aquí se puede agregar lógica para parpadear LEDs, leer botones, etc.
        if((ticksGet() - ticks)>= 1)
        {
            ticks = ticksGet();
            button_process(&sw); // Procesa la máquina de estados del botón.
        }

        if(sw.flags & 1)
        {
            sw.flags &=~ 1;
            // todo

        }
    }
}

/**
 * @brief Redirecciona printf al canal ITM para debugging.
 *
 * Esta función redirecciona la salida estándar al canal ITM (Instrumentation Trace Macrocell),
 * permitiendo que las sentencias printf se muestren en un depurador.
 *
 * @param ch: El carácter a ser enviado.
 * @return int: El carácter enviado.
 */
// Redirección de printf al canal ITM para debug
int __io_putchar(int ch){
    /*Cortex-M3/M4/M7/M33/23...*/
    ITM_SendChar(ch);
    return ch;
}
