/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

//----------------------------------------------------------------------------
// Includes
//----------------------------------------------------------------------------
#include <stdint.h>
#include "main.h"
#include "stm32f4xx.h"//CMSIS
#include <stdio.h>

//----------------------------------------------------------------------------
// defines
//----------------------------------------------------------------------------

//----------------------------------------------------------------------------
// constant
//----------------------------------------------------------------------------
#define SYSTICK_CTRL *((volatile uint32_t *)(0xE000E010))

#define SYSCON0 *((volatile uint32_t *)(0x400740C4))
/**
 * ->variables
 * volatile
 * - accedido por el procesador de forma rapida
 * - para hacer referencia a registros o hardware
 *   la variable puede ser modificada por el software o programa o puede ser modificado
 *   por un agente externo (hardware)
 * extern
 *  definido en otro lado(archivo)
 * static
 *  variable solo visible dentro del archivo o funcion
 */
//----------------------------------------------------------------------------
// global variables
//----------------------------------------------------------------------------
static volatile uint32_t uwTick = 0;
//----------------------------------------------------------------------------
// function prototype
//----------------------------------------------------------------------------
void app_clock_config(uint8_t source);
void delay_ms(uint32_t delay);

void SysTick_Handler(void)
{
	uwTick += 1;
}

static inline uint32_t getTicks (void)
{
	return uwTick;
}

void EXTI9_5_IRQHandler (void) //5, 9
{
	if(EXTI->PR & EXTI_PR_PR5)
	{
		//clear
		EXTI->PR |= EXTI_PR_PR5;
		//todo:

	}
	else if(EXTI->PR & EXTI_PR_PR6)
	{
		//clear
		EXTI->PR |= EXTI_PR_PR6;
		//todo:

	}
}
//----------------------------------------------------------------------------
// main
//----------------------------------------------------------------------------
int main(void)
{
	uint32_t ticks = 0;
	/**
	 * NOMBRE DE BLOQUE -> NOMBRE DE REGISTRO
	 */
	app_clock_config(APP_USE_PLL);

	SysTick_Config(SystemCoreClock / 1000);
	NVIC_SetPriority(SysTick_IRQn, 15);

	//Secciones criticas de codigo

	/**
	 * 4 sensores digitales
	 * PB4 -> EXTI4
	 * PC3 -> EXTI3
	 * PD5 -> EXTI5
	 * PE7 -> EXTI7
	 *
	 * PA4 ->EXTI4 (PB4,PC4, ...)
	 * PA5 ->EXTI5
	 * PA6 ->EXTI6
	 * PA7 ->EXTI7
	 */
	NVIC_EnableIRQ(EXTI9_5_IRQn);
	/**
	 * 1. habilitar y configurar los registros locales
	 * EXTI-> IMR, F, R
	 *
	 * 2. habilitar la interrupcion dentro de la NVIC
	 * NVIC_EnableIrq()
	 */

	/**
	 * funciones
	 * -> Bare metal
	 * cmsis (registros)
	 *
	 * -> hal drivers
	 * HAL_EXTI_XXX()
	 * -> Low layer
	 * LL_XXX_XXX (menor footprint)
	 * macros
	 * __HAL_TIM_SET_COMPARE(HANDLE, CH1, ,10)
	 * __LL_TIM_XXX
	 */
	/* Loop forever */
	for(;;)
	{
		if((getTicks() - ticks )> 100)
		{
			ticks = getTicks() ;
			GPIOD->ODR ^= GPIO_ODR_OD15;
		}

	}
}

//----------------------------------------------------------------------------
// function definition
//----------------------------------------------------------------------------
void delay_ms(uint32_t delay)
{
	for(uint32_t i = 0; i<delay; i++)
	{
		while(!(SysTick->CTRL & SysTick_CTRL_COUNTFLAG_Msk)); //loop (1ms)

	}
}


void app_clock_config(uint8_t source)
{

	//Switch Internal clock
	RCC->CR |= RCC_CR_HSION;
	while((RCC->CR & RCC_CR_HSIRDY) == 0);

	RCC->CFGR &=~ RCC_CFGR_SW;
	RCC->CFGR |= RCC_CFGR_SWS_HSI;
	while((RCC->CFGR & RCC_CFGR_SWS_HSI) != (RCC_CFGR_SWS_HSI));
	FLASH->ACR &=~ FLASH_ACR_LATENCY;
	//HSI16->Por defecto

	switch(source)
	{
	case APP_USE_HSE:
	{
		//HSE on
		RCC->CR |= RCC_CR_HSEON;
		while(!(RCC->CR & RCC_CR_HSERDY));
		//select clock
		RCC->CFGR |= RCC_CFGR_SW_HSE;
		while((RCC->CFGR & RCC_CFGR_SWS_HSE) != (RCC_CFGR_SWS_HSE));

		break;
	}
	case APP_USE_MSI:
	{

	}
	case APP_USE_PLL:
	{
		//PLL off
		RCC->CR &=~ RCC_CR_PLLON;
		while(RCC->CR & RCC_CR_PLLRDY);
		//configurar los valores del PLL
		/**
		 * fclock_p = ((16/8 ) * 168 )/2 = 168MHZ
		 */
		//source
		RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLSRC;
		RCC->PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSI;
		//M
		RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLM;
		RCC->PLLCFGR |= RCC_PLLCFGR_PLLM_3; //BITS (bit 3) 0b1000->8
		//N
		RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLN;
		RCC->PLLCFGR |= 168<<RCC_PLLCFGR_PLLN_Pos;
		//P
		RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLP;
		//Valor maximo del bus APB1(42MHZ)
		RCC->CFGR &=~ RCC_CFGR_PPRE1;
		RCC->CFGR |= RCC_CFGR_PPRE1_DIV4;
		//valor maximo del bus APB2(84MHZ)
		RCC->CFGR &=~ RCC_CFGR_PPRE2;
		RCC->CFGR |= RCC_CFGR_PPRE2_DIV2;
		//latencia
		FLASH->ACR &=~ FLASH_ACR_LATENCY;
		FLASH->ACR |= FLASH_ACR_LATENCY_5WS;
		//seleccionar la fuente
		RCC->CR |= RCC_CR_PLLON;
		while(!(RCC->CR & RCC_CR_PLLRDY));

		RCC->CFGR &=~RCC_CFGR_SW;
		RCC->CFGR |= RCC_CFGR_SW_PLL;
		while((RCC->CFGR & RCC_CFGR_SWS_PLL) != (RCC_CFGR_SWS_PLL));
		break;
	}
	}

	uint8_t temp = RCC->CFGR & 0x3; //[1:0]

	//update core clock
	SystemCoreClockUpdate();

	switch(temp)
	{
	case APP_USE_HSI:
		printf("la aplicacion esta usando HSI:%lu\r\n", SystemCoreClock);
		break;
	case APP_USE_HSE:
		printf("la aplicacion esta usando HSE:%lu\r\n",SystemCoreClock);
		break;
	case APP_USE_PLL:
		printf("la aplicacion esta usando PLL:%lu\r\n", SystemCoreClock);
		break;
	}
}
int __io_putchar(int ch)
{
	//aplica: ARM CORTEX-M3/4/7/33..
	//No aplica para los CORTEX-M0/M0+
	//SWO (PB3--->stlink)
	ITM_SendChar(ch);

	return ch;
}
