/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "stm32f4xx.h"//CMSIS
#include <stdio.h>




void app_clock_config(uint8_t source);


int main(void)
{
	/**
	 * NOMBRE DE BLOQUE -> NOMBRE DE REGISTRO
	 */
	app_clock_config(APP_USE_PLL);

	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

	/* Loop forever */
	for(;;);
}

void app_clock_config(uint8_t source)
{

	//Switch Internal clock
	RCC->CR |= RCC_CR_HSION;
	while((RCC->CR & RCC_CR_HSIRDY) == 0);

	RCC->CFGR &=~ RCC_CFGR_SW;
	RCC->CFGR |= RCC_CFGR_SWS_HSI;
	while((RCC->CFGR & RCC_CFGR_SWS_HSI) != (RCC_CFGR_SWS_HSI));
	FLASH->ACR &=~ FLASH_ACR_LATENCY;
	//HSI16->Por defecto

	switch(source)
	{
	case APP_USE_HSE:
	{
		//HSE on
		RCC->CR |= RCC_CR_HSEON;
		while(!(RCC->CR & RCC_CR_HSERDY));
		//select clock
		RCC->CFGR |= RCC_CFGR_SW_HSE;
		while((RCC->CFGR & RCC_CFGR_SWS_HSE) != (RCC_CFGR_SWS_HSE));

		break;
	}
	case APP_USE_MSI:
	{

	}
	case APP_USE_PLL:
	{
		//PLL off
		RCC->CR &=~ RCC_CR_PLLON;
		while(RCC->CR & RCC_CR_PLLRDY);
		//configurar los valores del PLL
		/**
		 * fclock_p = ((16/8 ) * 168 )/2 = 168MHZ
		 */
		//source
		RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLSRC;
		RCC->PLLCFGR |= RCC_PLLCFGR_PLLSRC_HSI;
		//M
		RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLM;
		RCC->PLLCFGR |= RCC_PLLCFGR_PLLM_3; //BITS (bit 3) 0b1000->8
		//N
		RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLN;
		RCC->PLLCFGR |= 168<<RCC_PLLCFGR_PLLN_Pos;
		//P
		RCC->PLLCFGR &=~ RCC_PLLCFGR_PLLP;
		//Valor maximo del bus APB1(42MHZ)
		RCC->CFGR &=~ RCC_CFGR_PPRE1;
		RCC->CFGR |= RCC_CFGR_PPRE1_DIV4;
		//valor maximo del bus APB2(84MHZ)
		RCC->CFGR &=~ RCC_CFGR_PPRE2;
		RCC->CFGR |= RCC_CFGR_PPRE2_DIV2;
		//latencia
		FLASH->ACR &=~ FLASH_ACR_LATENCY;
		FLASH->ACR |= FLASH_ACR_LATENCY_5WS;
		//seleccionar la fuente
		RCC->CR |= RCC_CR_PLLON;
		while(!(RCC->CR & RCC_CR_PLLRDY));

		RCC->CFGR &=~RCC_CFGR_SW;
		RCC->CFGR |= RCC_CFGR_SW_PLL;
		while((RCC->CFGR & RCC_CFGR_SWS_PLL) != (RCC_CFGR_SWS_PLL));
		break;
	}
	}

	uint8_t temp = RCC->CFGR & 0x3; //[1:0]

	//update core clock
	SystemCoreClockUpdate();

	switch(temp)
	{
	case APP_USE_HSI:
		printf("la aplicacion esta usando HSI:%lu\r\n", SystemCoreClock);
		break;
	case APP_USE_HSE:
		printf("la aplicacion esta usando HSE:%lu\r\n",SystemCoreClock);
		break;
	case APP_USE_PLL:
		printf("la aplicacion esta usando PLL:%lu\r\n", SystemCoreClock);
		break;
	}
}
int __io_putchar(int ch)
{
	//aplica: ARM CORTEX-M3/4/7/33..
	//No aplica para los CORTEX-M0/M0+
	//SWO (PB3--->stlink)
	ITM_SendChar(ch);

	return ch;
}
