/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"
#include <stdio.h>


#define RCC_CR *((volatile uint32_t *)(0x40023800))


typedef struct{
	volatile uint32_t CR;		//0x00
	volatile uint32_t PLLCFGR;	//0x04
	volatile uint32_t CFGR;		//0x08
}RCC_Def_t;

#define rcc 				((RCC_Def_t *)(0x40023800))


int main(void)
{
	/*registro de control*/
	//CR
	RCC->CR |= RCC_CR_HSEON; //1<<16;(8MHZ)
	//	RCC->CR |= RCC_CR_HSEBYP;//modo bypass (nucleo 64)
	while(!(RCC->CR & RCC_CR_HSERDY));


	/*registro de configuracion pll*/
	//PLLCFGR
	RCC->PLLCFGR |= 1<<22;

	//M = 8
	RCC->PLLCFGR &=~(RCC_PLLCFGR_PLLM);
	RCC->PLLCFGR |= 8;
	//N = 336
	RCC->PLLCFGR &=~ (RCC_PLLCFGR_PLLN);
	RCC->PLLCFGR |= 336<<(RCC_PLLCFGR_PLLN_Pos);
	//P = 2
	RCC->PLLCFGR &=~ (RCC_PLLCFGR_PLLP);

	/**
	 * SYSCLK = ((8MHZ/8) * 336)/ 2 = 168MHZ
	 */
	//PLL
	RCC->CR |= RCC_CR_PLLON;
	while(!(RCC->CR & RCC_CR_PLLRDY));

	//APB1 (42MHZ)
	RCC->CFGR &=~ RCC_CFGR_PPRE1;
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV4;
	//APB2(84MHZ)
	RCC->CFGR &=~ RCC_CFGR_PPRE2;
	RCC->CFGR |= RCC_CFGR_PPRE2_DIV2;
	/*Configurar la latencia de la flash*/
	/*configure flash latency*/
	FLASH->ACR &=~ FLASH_ACR_LATENCY;
	FLASH->ACR |= FLASH_ACR_LATENCY_5WS;
	/*registro de configuracion y prescaler*/
	//CFGR
	RCC->CFGR |= RCC_CFGR_SW_PLL;
	while(!(RCC->CFGR & RCC_CFGR_SWS));


	SystemCoreClockUpdate();

	for(;;){

	}
}
